### ISSUE TITLE
Error with "conversion from ‘Sophus::SE3f {aka Sophus::SE3<float>}’ to non-scalar type ‘cv::Mat’ requested"

### ISSUE THREAD

**Issue by DereLiu** [duncanrhamill/oakd_orbslam3#8]
/home/yan/Desktop/oakd/oakd_orbslam3/src/main.cpp: In function ‘int main(int, char**)’:
/home/yan/Desktop/oakd/oakd_orbslam3/src/main.cpp:197:44: error: conversion from ‘Sophus::SE3f {aka Sophus::SE3<float>}’ to non-scalar type ‘cv::Mat’ requested
         cv::Mat raw_pose = SLAM.TrackStereo(rectif_left,rectif_right,frame_timestamp_s);
                            ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CMakeFiles/oakd_orbslam3.dir/build.make:75: recipe for target 'CMakeFiles/oakd_orbslam3.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/oakd_orbslam3.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:101: recipe for target 'CMakeFiles/oakd_orbslam3.dir/all' failed
make[1]: *** [CMakeFiles/oakd_orbslam3.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

My teacher ask me to build this project but this error occurred when I run `make`.
Why did this error occur and how do I fix it?
Is that means I shouldn't built it with the version of opencv4?
@duncanrhamill

**Comment by bchuh** [comment]
Your teacher is ridiculous

**Comment by DereLiu** [comment]
> /home/yan/Desktop/oakd/oakd_orbslam3/src/main.cpp: In function ‘int main(int, char**)’: /home/yan/Desktop/oakd/oakd_orbslam3/src/main.cpp:197:44: error: conversion from ‘Sophus::SE3f {aka Sophus::SE3}’ to non-scalar type ‘cv::Mat’ requested cv::Mat raw_pose = SLAM.TrackStereo(rectif_left,rectif_right,frame_timestamp_s); ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ CMakeFiles/oakd_orbslam3.dir/build.make:75: recipe for target 'CMakeFiles/oakd_orbslam3.dir/src/main.cpp.o' failed make[2]: *** [CMakeFiles/oakd_orbslam3.dir/src/main.cpp.o] Error 1 CMakeFiles/Makefile2:101: recipe for target 'CMakeFiles/oakd_orbslam3.dir/all' failed make[1]: *** [CMakeFiles/oakd_orbslam3.dir/all] Error 2 Makefile:135: recipe for target 'all' failed make: *** [all] Error 2
> 
> My teacher ask me to build this project but this error occurred when I run `make`. Why did this error occur and how do I fix it? Is that means I shouldn't built it with the version of opencv4? @duncanrhamill

So, I get rid of this problem by changing the OpenCV version, but here is another problem.
------------------------------------------------------------------------------------------------------------------------------------
[ 97%] Building CXX object CMakeFiles/oakd_orbslam3.dir/src/util.cpp.o
[100%] Linking CXX executable bin/oakd_orbslam3
CMakeFiles/oakd_orbslam3.dir/src/main.cpp.o：在函数‘main’中：
/home/yan/桌面/oakd/oakd_orbslam3/src/main.cpp:136：对‘cv::ximgproc::createDisparityWLSFilterGeneric(bool)’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/oakd_orbslam3.dir/build.make:158: recipe for target 'bin/oakd_orbslam3' failed
make[2]: *** [bin/oakd_orbslam3] Error 1
CMakeFiles/Makefile2:101: recipe for target 'CMakeFiles/oakd_orbslam3.dir/all' failed
make[1]: *** [CMakeFiles/oakd_orbslam3.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by AreteQin** [comment]
You can solve the problem using following codes:
```
    Sophus::SE3f Tcw = mpSLAM->TrackMonocular(cv_ptr->image,cv_ptr->header.stamp.toSec());
    cv::Mat Tcw_cv = cv::Mat(4, 4, CV_32F, Tcw.matrix().data());
```

**Comment by AylonD** [comment]
Hi, i get a similar error when building the project, posted the problem here:
https://github.com/duncanrhamill/oakd_orbslam3/issues/11

I tried using the codes you suggested but got the following errors:
![תמונה של WhatsApp‏ 2023-09-27 בשעה 12 15 46](https://github.com/duncanrhamill/oakd_orbslam3/assets/101047444/4845d545-cbce-459a-91d6-0505c87e6e2d)

I would really appreciate your help!

**Comment by BALA22-cyber** [comment]
replace the following with 


        // cv::Mat raw_pose = SLAM.TrackStereo(
        //     rectif_left,
        //     rectif_right,
        //     frame_timestamp_s
        // );

the below lines 

        Sophus::SE3f raw_pose_sophus = SLAM.TrackStereo(
            rectif_left,
            rectif_right,
            frame_timestamp_s
        );

        // Convert Sophus::SE3f to cv::Mat (4x4 transformation matrix)
        cv::Mat raw_pose = (cv::Mat_<float>(4,4) <<
        raw_pose_sophus.rotationMatrix()(0,0), raw_pose_sophus.rotationMatrix()(0,1), raw_pose_sophus.rotationMatrix()(0,2), raw_pose_sophus.translation()(0),
        raw_pose_sophus.rotationMatrix()(1,0), raw_pose_sophus.rotationMatrix()(1,1), raw_pose_sophus.rotationMatrix()(1,2), raw_pose_sophus.translation()(1),
        raw_pose_sophus.rotationMatrix()(2,0), raw_pose_sophus.rotationMatrix()(2,1), raw_pose_sophus.rotationMatrix()(2,2), raw_pose_sophus.translation()(2),
        0, 0, 0, 1);
